---
title: "Session_01"
output: html_document
date: "2025-07-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# dnorm(x,mean = 0,log = FALSE)
# pnorm(q,mean=0,sd=1,lower.tail = TRUE,log.p = )
# qnorm()
# rnorm()
```

```{r}
# x: vector of quantiles.
# mean: vector of means.
# sd: vector standard deviation.

dnorm(10,mean = 0,log = FALSE)
```
```{r}
# n: number of datasets to be simulated
# mean: vector of means.
# sd: vector standard deviation.

set.seed(123)
rnorm(10,20,30)
```
```{r}

pnorm(0.5,mean=0,sd=1,lower.tail = TRUE,log.p =FALSE )
```
```{r}
#  p: It represents the significance level to be used
# mean: vector of means.
# sd: vector standard deviation.
#  lower.tail = TRUE: Then the probability to the left of p in the normal distribution is returned. 

qnorm(.95, mean=0, sd=1)
```
### Excercise:

```{r}
rpois(10,1)
```

```{r}
runif(100,min = 0,max = 10)
```
```{r}
set.seed(123)
x=rnorm(100,0,1)
y=0.5 + 2 * x+ rnorm(100,0,4)

library(ggplot2)
df=data.frame(y,x)
library(ggplot2)
ggplot(df,aes(x,y))+geom_point()
```
```{r}
model = lm (y~x ,data = df)
model
```


```{r}
step(model)
```
```{r}
summary(model)
```

### Excercise 2:

```{r}
set.seed(123)
x=runif(100,0,1)
y=0.5 + 2 * x+ rnorm(100,0,4)

library(ggplot2)
df2=data.frame(y,x)
library(ggplot2)
ggplot(df2,aes(x,y))+geom_point()
```
```{r}
model2= lm(y~x,data=df2)
model2
```

## Random Sample

```{r}
set.seed(1)
sample(1:10,4)
```

```{r}
#doesnt have to be a numbers
sample(letters,5)
```
### Permutaion


```{r}
sample(1:10)
```

```{r}
sample(1:10)
```
```{r}
sample(1:10,replace = T) # default replace false
```
```{r}
library(datasets)
data("airquality")
head(airquality)
```

```{r}
set.seed(20)

idx=seq_len(nrow(airquality))
samp=sample(idx,6)
airquality[samp,]
```

